name = "KnowledgeGraphRecipe"
uuid = "6f2558d9-7617-4091-b249-0c28cc08e8a6"
version = "0.1.0"
authors = ["Emmanuel_R8 <emmanuel.rialland@gmail.com>"]

[deps]
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"

[compat]
julia = "1.8"
GraphRecipes = "0.5"
Plots = "1.0"
Colors = "0.12"
